# Generated by Django 3.2 on 2024-11-08 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('dificultad', models.CharField(max_length=30)),
                ('tematica', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_lanz', models.DateField()),
                ('desarrolladora', models.CharField(max_length=100)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Consola', 'Consola'), ('PC', 'PC'), ('Movil', 'Movil')], max_length=20)),
                ('generacion', models.CharField(max_length=20)),
                ('almacenamiento', models.IntegerField()),
                ('fabricante', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
