# Generated by Django 3.2 on 2024-11-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='formato',
            field=models.CharField(choices=[('MULTIJUGADOR', 'Multijugador'), ('SOLO', 'Solo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='precio',
            field=models.FloatField(max_length=5),
        ),
    ]
