# Generated by Django 3.2 on 2024-11-10 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_auto_20241109_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='generos',
            field=models.ManyToManyField(related_name='juegos', to='Aplicacion.Genero'),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='Aplicacion.plataforma'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
