# Generated by Django 3.2 on 2024-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_remove_juego_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='generos',
            field=models.ManyToManyField(related_name='juegos', to='Aplicacion.Genero'),
        ),
    ]
