# Generated by Django 3.2 on 2024-11-11 22:36

import Aplicacion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_juego_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='almacenamiento',
            field=models.IntegerField(validators=[Aplicacion.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), Aplicacion.models.validate_positive]),
        ),
    ]
