# Generated by Django 3.2 on 2024-11-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_auto_20241111_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(related_name='juegos', to='Aplicacion.Plataforma'),
        ),
    ]
